backend:
  name: github
  branch: main
  locale: 'ja'
media_folder: ".vuepress/public/media"
public_folder : "/media"

publish_mode: editorial_workflow

collections:
  - name: "Blog-2021" 
    label: "Blog-2021"
    folder: "src/_posts/2021"
    create: true
    slug: mm-dd
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"} 
      - {label: "Body", name: "body", widget: "markdown"}
