backend:
  name: git-gateway
  branch: main
  locale: 'ja'
media_folder: ".vuepress/public/media"
public_folder : "/media"

publish_mode: editorial_workflow

collections:
  - name: "Blog-2021" 
    label: "Blog-2021"
    folder: "src/_posts/2021"
    create: true
    editor:
      preview: true
    slug: "{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"} 
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Thumbnail", name: "socialImage", widget: image}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Slug", name: "slug", widget: "number", default: "001"}
  
  - name: "Blog-2022" 
    label: "Blog-2022"
    folder: "src/_posts/2022"
    create: true
    slug: "{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"} 
      - {label: "Body", name: "body", widget: "markdown"}
