name: Build and Deploy

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_REPO: Nakatai-0322/blog
        TARGET_BRANCH: builded
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: src/.vuepress/dist/
