name: Deploy

  # mainのプッシュ検知
on:
  push:
    branches:
    - main


  # 動かす環境や走らせて欲しいコマンドなど
  jobs:
    build-deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.cache/yarn
            key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
                ${{ runner.os }}-node-


        - name: install
          if: steps.cache.outputs.cache-hit != 'true'
          run: yarn install


        - name: build
          run: yarn src:build


        - name: deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist